"use client"

import { useEffect, useState } from "react"
import { Eye, EyeOff } from "lucide-react"

export function UsersClient() {
  const [users, setUsers] = useState<Record<string, unknown>[]>([])
  const [error, setError] = useState("")
  const [open, setOpen] = useState(false)
  const [showPassword, setShowPassword] = useState(false)
  async function load() { const response = await fetch("/api/users"); const json = await response.json(); if (!response.ok) setError(json.error ?? "Gagal mengambil user"); else setUsers(json.data ?? []) }
  useEffect(() => { load() }, [])
  async function submit(formData: FormData) { const response = await fetch("/api/users", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(formData)) }); if (!response.ok) { const json = await response.json(); setError(json.error ?? "Gagal membuat user"); return }; setOpen(false); setShowPassword(false); load() }
  return <><div className="panel"><div className="panel-head"><h2>Registered users</h2><button className="btn btn-primary" onClick={() => setOpen(true)}>Tambah user</button></div><div className="table-wrap"><table><thead><tr><th>Nama</th><th>Email</th><th>Role</th><th>Status</th></tr></thead><tbody>{users.map(user => <tr key={String(user.id)}><td>{String(user.full_name)}</td><td>{String(user.email)}</td><td>{String(user.role)}</td><td><span className="status status-active">Active</span></td></tr>)}</tbody></table>{error && <div className="error" style={{ margin: 16 }}>{error}</div>}</div></div>{open && <div style={{ position: "fixed", inset: 0, background: "#10233f88", display: "grid", placeItems: "center", padding: 20 }}><form className="panel panel-body stack" style={{ width: "min(440px, 100%)" }} action={submit}><h2 style={{ margin: 0 }}>Tambah user</h2><label className="field">Nama<input className="input" name="full_name" required /></label><label className="field">Email<input className="input" name="email" type="email" required /></label><label className="field">Password<span style={{ position: "relative", display: "block" }}><input className="input" style={{ width: "100%", paddingRight: 42 }} name="password" type={showPassword ? "text" : "password"} minLength={8} required /><button type="button" onClick={() => setShowPassword(value => !value)} aria-label={showPassword ? "Sembunyikan password" : "Tampilkan password"} style={{ position: "absolute", right: 10, top: "50%", transform: "translateY(-50%)", border: 0, background: "transparent", color: "var(--muted)", padding: 4, display: "grid", placeItems: "center" }}>{showPassword ? <EyeOff size={17} /> : <Eye size={17} />}</button></span></label><label className="field">Role<select className="select" name="role" defaultValue="staff"><option value="staff">Staff</option><option value="admin">Admin</option></select></label><div style={{ display: "flex", gap: 10 }}><button className="btn btn-primary">Simpan</button><button type="button" className="btn btn-secondary" onClick={() => { setOpen(false); setShowPassword(false) }}>Batal</button></div></form></div>}</>
}
