"use client"
import { useEffect, useState } from "react"
import { Plus, Search, Upload, Download } from "lucide-react"
import * as XLSX from "xlsx"
import type { Resource } from "@/lib/types"
type Field = { key: string; label: string; type?: string; required?: boolean }
export function ResourceClient({ resource, title, fields }: { resource: Resource; title: string; fields: Field[] }) { const [rows, setRows] = useState<Record<string, unknown>[]>([]); const [q, setQ] = useState(""); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); async function load(search = "") { setLoading(true); const response = await fetch(`/api/${resource}?q=${encodeURIComponent(search)}`); const json = await response.json(); if (!response.ok) setError(json.error ?? "Gagal mengambil data"); else setRows(json.data ?? []); setLoading(false) } useEffect(() => { load() }, [])
  function exportRows() { const sheet = XLSX.utils.json_to_sheet(rows); const book = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(book, sheet, resource); XLSX.writeFile(book, `${resource}-export.xlsx`) }
  async function importFile(file: File) { const workbook = XLSX.read(await file.arrayBuffer()); const data = XLSX.utils.sheet_to_json<Record<string, unknown>>(workbook.Sheets[workbook.SheetNames[0]]); for (const row of data) await fetch(`/api/${resource}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(row) }); await load(q) }
  return <><div style={{ display: "flex", justifyContent: "space-between", alignItems: "end", marginBottom: 24, gap: 15, flexWrap: "wrap" }}><div><div className="eyebrow">Operational register</div><h1 style={{ margin: "5px 0 0", fontSize: 26 }}>{title}</h1></div><div className="toolbar" style={{ margin: 0 }}><label className="btn btn-secondary"><Upload size={14} /> Import Excel<input hidden type="file" accept=".xlsx,.xls,.csv" onChange={e => e.target.files?.[0] && importFile(e.target.files[0])} /></label><button className="btn btn-secondary" onClick={exportRows}><Download size={14} /> Export</button><button className="btn btn-primary" onClick={() => setOpen(true)}><Plus size={14} /> Tambah</button></div></div><div className="panel"><div className="panel-body"><div className="toolbar"><div style={{ position: "relative" }}><Search size={15} style={{ position: "absolute", left: 11, top: 11, color: "var(--muted)" }} /><input className="input" style={{ paddingLeft: 34 }} placeholder="Cari data..." value={q} onChange={e => { setQ(e.target.value); load(e.target.value) }} /></div>{error && <div className="error">{error}</div>}</div><div className="table-wrap">{loading ? <div className="empty">Memuat data...</div> : rows.length === 0 ? <div className="empty">Belum ada data. Tambahkan record pertama untuk memulai.</div> : <table><thead><tr>{fields.slice(0, 5).map(f => <th key={f.key}>{f.label}</th>)}<th>Status</th></tr></thead><tbody>{rows.map(row => <tr key={String(row.id)}>{fields.slice(0, 5).map(f => <td key={f.key}>{String(row[f.key] ?? "-")}</td>)}<td><span className={`status status-${String(row.status ?? row.status_layanan ?? "pending").toLowerCase().replaceAll(" ", "-")}`}>{String(row.status ?? row.status_layanan ?? "Pending")}</span></td></tr>)}</tbody></table>}</div></div></div>{open && <RecordForm resource={resource} fields={fields} onClose={() => setOpen(false)} onSaved={() => { setOpen(false); load(q) }} />}</> }
function RecordForm({ resource, fields, onClose, onSaved }: { resource: Resource; fields: Field[]; onClose: () => void; onSaved: () => void }) { const [error, setError] = useState(""); const [saving, setSaving] = useState(false); async function submit(formData: FormData) { const body = Object.fromEntries(formData); if (resource !== "sites" && !body.site_id) { setError("Site wajib dipilih melalui Site ID."); return }; setSaving(true); const response = await fetch(`/api/${resource}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const json = await response.json(); if (!response.ok) { setError(json.error ?? "Data tidak valid"); setSaving(false); return }; onSaved() }; return <div style={{ position: "fixed", inset: 0, background: "#10233f88", display: "grid", placeItems: "center", padding: 20, zIndex: 5 }}><div className="panel" style={{ width: "min(720px, 100%)", maxHeight: "90vh", overflow: "auto" }}><div className="panel-head"><h2>Tambah data</h2><button className="btn btn-secondary" onClick={onClose}>Tutup</button></div><form className="panel-body form-grid" action={submit}>{resource !== "sites" && <label className="field wide">Site ID<input className="input" name="site_id" required placeholder="UUID site" /></label>}{fields.map(field => <label className={`field ${field.type === "textarea" ? "wide" : ""}`} key={field.key}>{field.label}{field.type === "textarea" ? <textarea className="textarea" name={field.key} required={field.required} /> : <input className="input" name={field.key} type={field.type ?? "text"} required={field.required} />}</label>)}{error && <div className="error wide">{error}</div>}<div className="wide"><button className="btn btn-primary" disabled={saving}>{saving ? "Menyimpan..." : "Simpan data"}</button></div></form></div></div> }
