"use client"

import { useEffect, useState } from "react"
import { Download, Edit3, Plus, Search, Trash2, Upload } from "lucide-react"
import * as XLSX from "xlsx"
import { useToast } from "@/components/toast"
import { schemas, siteSchema, validationMessage } from "@/lib/validation"
import type { Resource } from "@/lib/types"

type Field = { key: string; label: string; type?: string; required?: boolean }
type Row = Record<string, unknown>
type ApiError = { error?: string; details?: unknown }

function schemaFor(resource: Resource) { return resource === "sites" ? siteSchema : schemas[resource] }
function fieldMessage(json: ApiError, fallback: string) { return json.details ? validationMessage(json.details) : (json.error ?? fallback) }

export function ResourceClient({ resource, title, fields }: { resource: Resource; title: string; fields: Field[] }) {
  const { showToast } = useToast(); const [rows, setRows] = useState<Row[]>([]); const [q, setQ] = useState(""); const [editing, setEditing] = useState<Row | null>(null); const [adding, setAdding] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState("")
  async function load(search = "") { try { setLoading(true); const response = await fetch(`/api/${resource}?q=${encodeURIComponent(search)}`); const json = await response.json() as ApiError & { data?: Row[] }; if (!response.ok) throw new Error(fieldMessage(json, "Data gagal dimuat.")); setError(""); setRows(json.data ?? []) } catch (cause) { const message = cause instanceof Error ? cause.message : "Data gagal dimuat."; setError(message); showToast("Gagal memuat data", message, "error") } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  function exportRows() { const sheet = XLSX.utils.json_to_sheet(rows); const book = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(book, sheet, resource); XLSX.writeFile(book, `${resource}-export.xlsx`); showToast("Export berhasil", `${rows.length} baris ${title.toLowerCase()} berhasil diunduh.`, "success") }
  async function importFile(file: File) { try { const workbook = XLSX.read(await file.arrayBuffer()); const firstSheet = workbook.Sheets[workbook.SheetNames[0]]; if (!firstSheet) throw new Error("Workbook tidak memiliki sheet yang bisa dibaca."); const data = XLSX.utils.sheet_to_json<Row>(firstSheet); if (!data.length) throw new Error("File Excel kosong. Isi minimal satu baris data."); let failures = 0; let firstError = ""; for (const [index, row] of data.entries()) { const response = await fetch(`/api/${resource}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(row) }); if (!response.ok) { failures++; const json = await response.json() as ApiError; if (!firstError) firstError = `Baris ${index + 2}: ${fieldMessage(json, "data tidak valid")}` } } if (failures) showToast("Import perlu diperbaiki", `${failures} baris gagal. ${firstError}`, "error"); else showToast("Import berhasil", `${data.length} baris berhasil ditambahkan.`, "success"); await load(q) } catch (cause) { const message = cause instanceof Error ? cause.message : "File Excel tidak dapat diproses."; setError(message); showToast("Import gagal", `${message} Gunakan .xlsx, .xls, atau .csv dengan kolom sesuai form.`, "error") } }
  async function archive(row: Row) { if (!window.confirm("Arsipkan data ini? Data tidak akan tampil di daftar aktif.")) return; try { const response = await fetch(`/api/${resource}/${row.id}`, { method: "DELETE" }); const json = await response.json() as ApiError; if (!response.ok) throw new Error(fieldMessage(json, "Data gagal diarsipkan.")); showToast("Data diarsipkan", "Record berhasil dipindahkan dari daftar aktif.", "success"); await load(q) } catch (cause) { showToast("Gagal mengarsipkan", cause instanceof Error ? cause.message : "Coba lagi.", "error") } }
  return <><div style={{ display: "flex", justifyContent: "space-between", alignItems: "end", marginBottom: 24, gap: 15, flexWrap: "wrap" }}><div><div className="eyebrow">Operational register</div><h1 style={{ margin: "5px 0 0", fontSize: 26 }}>{title}</h1></div><div className="toolbar" style={{ margin: 0 }}><label className="btn btn-secondary"><Upload size={14} /> Import Excel<input hidden type="file" accept=".xlsx,.xls,.csv" onChange={event => { const file = event.target.files?.[0]; if (file) void importFile(file); event.currentTarget.value = "" }} /></label><button className="btn btn-secondary" onClick={exportRows}><Download size={14} /> Export</button><button className="btn btn-primary" onClick={() => setAdding(true)}><Plus size={14} /> Tambah</button></div></div><div className="panel"><div className="panel-body"><div className="toolbar"><div style={{ position: "relative" }}><Search size={15} style={{ position: "absolute", left: 11, top: 11, color: "var(--muted)" }} /><input className="input" style={{ paddingLeft: 34 }} placeholder="Cari data..." value={q} onChange={event => { setQ(event.target.value); void load(event.target.value) }} /></div>{error && <div className="error">{error}</div>}</div><div className="table-wrap">{loading ? <div className="empty">Memuat data...</div> : rows.length === 0 ? <div className="empty">Belum ada data. Tambahkan record pertama untuk memulai.</div> : <table><thead><tr>{fields.slice(0, 5).map(field => <th key={field.key}>{field.label}</th>)}<th>Status</th><th>Aksi</th></tr></thead><tbody>{rows.map(row => <tr key={String(row.id)}>{fields.slice(0, 5).map(field => <td key={field.key}>{String(row[field.key] ?? "-")}</td>)}<td><span className={`status status-${String(row.status ?? row.status_layanan ?? "pending").toLowerCase().replaceAll(" ", "-")}`}>{String(row.status ?? row.status_layanan ?? "Pending")}</span></td><td><button className="btn btn-secondary" onClick={() => setEditing(row)} aria-label="Edit"><Edit3 size={13} /></button> <button className="btn btn-danger" onClick={() => void archive(row)} aria-label="Arsipkan"><Trash2 size={13} /></button></td></tr>)}</tbody></table>}</div></div></div>{(adding || editing) && <RecordForm resource={resource} fields={fields} initial={editing} onClose={() => { setAdding(false); setEditing(null) }} onSaved={() => { setAdding(false); setEditing(null); void load(q) }} />}</>
}

function RecordForm({ resource, fields, initial, onClose, onSaved }: { resource: Resource; fields: Field[]; initial: Row | null; onClose: () => void; onSaved: () => void }) {
  const { showToast } = useToast(); const [error, setError] = useState(""); const [saving, setSaving] = useState(false)
  async function submit(formData: FormData) { const body = Object.fromEntries([...formData.entries()].map(([key, value]) => [key, value === "" ? undefined : value])); const parsed = schemaFor(resource).safeParse(body); if (!parsed.success) { const message = parsed.error.issues[0]?.message ?? "Periksa format data."; setError(message); showToast("Data belum sesuai", message, "error"); return } try { setSaving(true); const method = initial ? "PATCH" : "POST"; const response = await fetch(initial ? `/api/${resource}/${initial.id}` : `/api/${resource}`, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(parsed.data) }); const json = await response.json() as ApiError; if (!response.ok) throw new Error(fieldMessage(json, "Data tidak dapat disimpan.")); showToast(initial ? "Data diperbarui" : "Data berhasil ditambahkan", "Perubahan tersimpan.", "success"); onSaved() } catch (cause) { const message = cause instanceof Error ? cause.message : "Data tidak dapat disimpan."; setError(message); showToast("Gagal menyimpan data", `${message} Saran: periksa format tanggal YYYY-MM-DD dan field wajib.`, "error") } finally { setSaving(false) } }
  return <div style={{ position: "fixed", inset: 0, background: "#1B232B88", display: "grid", placeItems: "center", padding: 20, zIndex: 5 }}><div className="panel" style={{ width: "min(720px, 100%)", maxHeight: "90vh", overflow: "auto" }}><div className="panel-head"><h2>{initial ? "Edit data" : "Tambah data"}</h2><button className="btn btn-secondary" onClick={onClose}>Tutup</button></div><form className="panel-body form-grid" action={submit}>{resource !== "sites" && <label className="field wide">Site ID<input className="input" name="site_id" defaultValue={String(initial?.site_id ?? "")} required placeholder="UUID site" /></label>}{fields.map(field => <label className={`field ${field.type === "textarea" ? "wide" : ""}`} key={field.key}>{field.label}{field.type === "textarea" ? <textarea className="textarea" name={field.key} defaultValue={String(initial?.[field.key] ?? "")} required={field.required} /> : <input className="input" name={field.key} type={field.type ?? "text"} defaultValue={String(initial?.[field.key] ?? "")} required={field.required} />}</label>)}{error && <div className="error wide">{error}</div>}<div className="wide"><button className="btn btn-primary" disabled={saving}>{saving ? "Menyimpan..." : "Simpan data"}</button></div></form></div></div>
}
