export type Role = "admin" | "staff"
export type Resource = "sites" | "cids" | "fabs" | "upgrades" | "maintenance"

export type Site = { id: string; no: number; nama_site: string; site_id: string; provinsi: string; kota_kabupaten: string; vlan: string; kapasitas_bandwidth: string; media_akses: string; pic_customer: string; no_telp_pic: string; pic_isp: string; tanggal_aktivasi: string | null; status_layanan: string; keterangan: string | null; created_at: string }
export type RecordRow = { id: string; site_id: string; status: string; notes: string | null; created_at: string; [key: string]: unknown }

export const resourceLabels: Record<Resource, string> = { sites: "Site Database", cids: "CID Tracking", fabs: "FAB / SO Tracking", upgrades: "Upgrade Bandwidth", maintenance: "Maintenance" }
export const resourceSubtitles: Record<Resource, string> = { sites: "Daftar seluruh site jaringan aktif", cids: "Database Circuit ID / Service Customer", fabs: "Daftar seluruh Formulir Berlangganan (FAB) / Service Order", upgrades: "Daftar seluruh permintaan peningkatan bandwidth", maintenance: "Pengelolaan aktivitas maintenance jaringan" }
export const resourceButtonLabel: Record<Resource, string> = { sites: "Site", cids: "CID", fabs: "FAB", upgrades: "Upgrade", maintenance: "Maintenance" }
export type Field = { key: string; label: string; type?: string; required?: boolean; virtual?: boolean; prefix?: string }
export const resourceFields: Record<Resource, Field[]> = {
  sites: [
    { key: "nama_site", label: "Nama Site", required: true }, { key: "site_id", label: "Site ID", required: true }, { key: "provinsi", label: "Provinsi", required: true }, { key: "kota_kabupaten", label: "Kota/Kabupaten", required: true }, { key: "vlan", label: "VLAN" }, { key: "kapasitas_bandwidth", label: "Kapasitas Bandwidth" }, { key: "media_akses", label: "Media Akses" }, { key: "pic_customer", label: "PIC Customer" }, { key: "no_telp_pic", label: "No Telp PIC" }, { key: "pic_isp", label: "PIC ISP" }, { key: "tanggal_aktivasi", label: "Tanggal Aktivasi", type: "date" }, { key: "status_layanan", label: "Status Layanan", required: true }, { key: "keterangan", label: "Keterangan", type: "textarea" }
  ],
  cids: [{ key: "cid_number", label: "CID Number", required: true }, { key: "customer", label: "Customer" }, { key: "site_code", label: "Site ID", virtual: true }, { key: "site_name", label: "Site Name", virtual: true }, { key: "service_type", label: "Jenis Layanan" }, { key: "bandwidth", label: "Bandwidth" }, { key: "vlan", label: "VLAN" }, { key: "ip_address", label: "IP Address" }, { key: "activation_date", label: "Tanggal Aktivasi", type: "date" }, { key: "status", label: "Status", required: true }, { key: "pic", label: "PIC" }, { key: "notes", label: "Catatan", type: "textarea" }],
  fabs: [{ key: "fab_number", label: "FAB / SO Number", required: true }, { key: "request_date", label: "Request Date", type: "date" }, { key: "target_date", label: "Target Date", type: "date" }, { key: "completion_date", label: "Completion Date", type: "date" }, { key: "status", label: "Status", required: true }, { key: "pic", label: "PIC" }, { key: "notes", label: "Notes", type: "textarea" }],
  upgrades: [{ key: "cid_number", label: "CID Number", virtual: true }, { key: "customer", label: "Customer", virtual: true }, { key: "site_name", label: "Site / POP", virtual: true }, { key: "current_bandwidth", label: "Existing BW", required: true }, { key: "requested_bandwidth", label: "Request BW", required: true }, { key: "request_date", label: "Tanggal Request", type: "date" }, { key: "target_date", label: "Target Date", type: "date" }, { key: "completion_date", label: "Completion Date", type: "date" }, { key: "status", label: "Status", required: true }, { key: "pic", label: "PIC" }, { key: "notes", label: "Catatan", type: "textarea" }],
  maintenance: [{ key: "no", label: "Ticket No", virtual: true, prefix: "MNT-" }, { key: "cid_number", label: "CID", virtual: true }, { key: "customer", label: "Customer", virtual: true }, { key: "site_name", label: "Site / POP", virtual: true }, { key: "maintenance_type", label: "Jenis", required: true }, { key: "impact", label: "Impact" }, { key: "scheduled_at", label: "Tanggal", type: "date" }, { key: "started_at", label: "Mulai", type: "date" }, { key: "completed_at", label: "Selesai", type: "date" }, { key: "status", label: "Status", required: true }, { key: "pic_vendor", label: "PIC" }, { key: "notes", label: "Catatan", type: "textarea" }]
}
