import { NextRequest, NextResponse } from "next/server"
import { desc, ilike, isNull } from "drizzle-orm"
import { requireUser } from "@/lib/auth"
import { auditLogs, tableMap } from "@/lib/db/schema"
import type { Resource } from "@/lib/types"
const resources: Resource[] = ["sites", "cids", "fabs", "upgrades", "maintenance"]
function snakeToCamel(value: Record<string, unknown>) { return Object.fromEntries(Object.entries(value).map(([key, val]) => [key.replace(/_([a-z])/g, (_, c) => c.toUpperCase()), val])) }
function camelToSnake(value: Record<string, unknown>) { return Object.fromEntries(Object.entries(value).map(([key, val]) => [key.replace(/[A-Z]/g, c => `_${c.toLowerCase()}`), val])) }
export async function GET(request: NextRequest, { params }: { params: Promise<{ resource: string }> }) { const { resource } = await params; if (!resources.includes(resource as Resource)) return NextResponse.json({ error: "Resource tidak ditemukan" }, { status: 404 }); const { db } = await requireUser(); const table = tableMap[resource as keyof typeof tableMap] as any; const query = request.nextUrl.searchParams.get("q") ?? ""; const rows = (query && resource === "sites" ? await db.select().from(table).where(ilike(table.namaSite, `%${query}%`)).orderBy(desc(table.createdAt)).limit(100) : await db.select().from(table).where(isNull(table.archivedAt)).orderBy(desc(table.createdAt)).limit(100)) as unknown as Record<string, unknown>[]; return NextResponse.json({ data: rows.map(camelToSnake) }) }
export async function POST(request: Request, { params }: { params: Promise<{ resource: string }> }) { const { resource } = await params; if (!resources.includes(resource as Resource)) return NextResponse.json({ error: "Resource tidak ditemukan" }, { status: 404 }); const { db, user } = await requireUser(); const table = tableMap[resource as keyof typeof tableMap] as any; const body = snakeToCamel(await request.json()); const result = await db.insert(table).values(body as any).returning(); const data = (Array.isArray(result) ? result[0] : undefined) as Record<string, unknown> | undefined; if (!data) return NextResponse.json({ error: "Gagal menyimpan data" }, { status: 400 }); await db.insert(auditLogs).values({ userId: user.id, action: "create", module: resource, recordId: data.id as string }); return NextResponse.json({ data: camelToSnake(data) }, { status: 201 }) }
