ALTER TABLE "fabs" ADD COLUMN IF NOT EXISTS "workflow_status" text DEFAULT 'draft' NOT NULL;
ALTER TABLE "fabs" ADD COLUMN IF NOT EXISTS "created_by" text;
ALTER TABLE "fabs" ADD COLUMN IF NOT EXISTS "submitted_at" timestamp with time zone;
ALTER TABLE "fabs" ADD COLUMN IF NOT EXISTS "approved_at" timestamp with time zone;
ALTER TABLE "fabs" ADD COLUMN IF NOT EXISTS "approved_by" text;
ALTER TABLE "fabs" ADD COLUMN IF NOT EXISTS "declaration_confirmed" boolean DEFAULT false NOT NULL;
ALTER TABLE "fabs" ALTER COLUMN "site_id" DROP NOT NULL;
CREATE INDEX IF NOT EXISTS "fabs_workflow_idx" ON "fabs" ("workflow_status");
CREATE INDEX IF NOT EXISTS "fabs_created_by_idx" ON "fabs" ("created_by");

CREATE TABLE IF NOT EXISTS "fab_service_requests" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "fab_id" uuid NOT NULL REFERENCES "fabs"("id") ON DELETE cascade, "sequence" integer NOT NULL, "site_id" uuid REFERENCES "sites"("id") ON DELETE set null, "requested_rfs_date" date, "created_at" timestamp with time zone DEFAULT now() NOT NULL, "updated_at" timestamp with time zone DEFAULT now() NOT NULL, CONSTRAINT "fab_service_requests_sequence_idx" UNIQUE("fab_id", "sequence"));
CREATE TABLE IF NOT EXISTS "fab_contacts" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "fab_id" uuid NOT NULL REFERENCES "fabs"("id") ON DELETE cascade, "service_request_id" uuid REFERENCES "fab_service_requests"("id") ON DELETE cascade, "role" text NOT NULL, "name" text, "department" text, "title" text, "email" text, "phone_code" text, "phone_number" text, "phone_extension" text, "mobile_code" text, "mobile_number" text, "birth_place" text, "birth_date" date, "id_type" text, "id_number" text, "id_expiry" date);
CREATE TABLE IF NOT EXISTS "fab_service_products" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "service_request_id" uuid NOT NULL REFERENCES "fab_service_requests"("id") ON DELETE cascade, "category" text NOT NULL, "product" text NOT NULL, "package" text, "unit" text NOT NULL, "quantity" numeric(12,2) NOT NULL, "delivery_scope" text, "uplink_required" boolean DEFAULT false NOT NULL, "space_m2" numeric(12,2), "rack_u" numeric(12,2), "power_kva" numeric(12,2));
CREATE TABLE IF NOT EXISTS "fab_service_endpoints" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "service_request_id" uuid NOT NULL REFERENCES "fab_service_requests"("id") ON DELETE cascade, "role" text NOT NULL, "country" text, "overseas_carrier" text, "company_name" text, "address" text, "latitude" numeric(9,6), "longitude" numeric(9,6), "pic_name" text, "phone" text, "email" text, CONSTRAINT "fab_service_endpoints_role_idx" UNIQUE("service_request_id", "role"));
CREATE TABLE IF NOT EXISTS "fab_billings" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "fab_id" uuid NOT NULL REFERENCES "fabs"("id") ON DELETE cascade, "term_months" integer, "billing_address" text, "currency" text DEFAULT 'IDR' NOT NULL, "vat_rate" numeric(5,2) DEFAULT '0' NOT NULL, CONSTRAINT "fab_billings_fab_idx" UNIQUE("fab_id"));
CREATE TABLE IF NOT EXISTS "fab_charge_lines" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "billing_id" uuid NOT NULL REFERENCES "fab_billings"("id") ON DELETE cascade, "type" text NOT NULL, "description" text, "service_amount" numeric(18,2) DEFAULT '0' NOT NULL, "port_amount" numeric(18,2) DEFAULT '0' NOT NULL, "local_access_amount" numeric(18,2) DEFAULT '0' NOT NULL, "on_demand_amount" numeric(18,2) DEFAULT '0' NOT NULL, "schedule_amount" numeric(18,2) DEFAULT '0' NOT NULL, "cpe_amount" numeric(18,2) DEFAULT '0' NOT NULL, "other_amount" numeric(18,2) DEFAULT '0' NOT NULL, "subtotal" numeric(18,2) DEFAULT '0' NOT NULL, "vat_amount" numeric(18,2) DEFAULT '0' NOT NULL, "total" numeric(18,2) DEFAULT '0' NOT NULL);
CREATE TABLE IF NOT EXISTS "fab_document_verifications" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "fab_id" uuid NOT NULL REFERENCES "fabs"("id") ON DELETE cascade, "document_type" text NOT NULL, "verified" boolean DEFAULT false NOT NULL, "verified_at" timestamp with time zone, "verified_by" text REFERENCES "user"("id") ON DELETE set null, CONSTRAINT "fab_document_verifications_type_idx" UNIQUE("fab_id", "document_type"));
