import { pgTable, text, integer, boolean, date, timestamp, index, uniqueIndex, uuid, numeric } from "drizzle-orm/pg-core"
export const authUser = pgTable("user", { id: text("id").primaryKey(), name: text("name").notNull(), email: text("email").notNull().unique(), emailVerified: boolean("email_verified").notNull().default(false), image: text("image"), createdAt: timestamp("created_at").notNull(), updatedAt: timestamp("updated_at").notNull() })
export const authSession = pgTable("session", { id: text("id").primaryKey(), expiresAt: timestamp("expires_at").notNull(), token: text("token").notNull().unique(), createdAt: timestamp("created_at").notNull(), updatedAt: timestamp("updated_at").notNull(), ipAddress: text("ip_address"), userAgent: text("user_agent"), userId: text("user_id").notNull().references(() => authUser.id, { onDelete: "cascade" }) }, t => ({ userIdx: index("session_user_idx").on(t.userId) }))
export const authAccount = pgTable("account", { id: text("id").primaryKey(), accountId: text("account_id").notNull(), providerId: text("provider_id").notNull(), userId: text("user_id").notNull().references(() => authUser.id, { onDelete: "cascade" }), accessToken: text("access_token"), refreshToken: text("refresh_token"), idToken: text("id_token"), accessTokenExpiresAt: timestamp("access_token_expires_at"), refreshTokenExpiresAt: timestamp("refresh_token_expires_at"), scope: text("scope"), password: text("password"), createdAt: timestamp("created_at").notNull(), updatedAt: timestamp("updated_at").notNull() }, t => ({ userIdx: index("account_user_idx").on(t.userId) }))
export const authVerification = pgTable("verification", { id: text("id").primaryKey(), identifier: text("identifier").notNull(), value: text("value").notNull(), expiresAt: timestamp("expires_at").notNull(), createdAt: timestamp("created_at"), updatedAt: timestamp("updated_at") }, t => ({ identifierIdx: index("verification_identifier_idx").on(t.identifier) }))
export const profiles = pgTable("profiles", { id: text("id").primaryKey().references(() => authUser.id, { onDelete: "cascade" }), fullName: text("full_name").notNull(), email: text("email").notNull(), role: text("role").notNull().default("staff"), isActive: boolean("is_active").notNull().default(true), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, t => ({ emailIdx: uniqueIndex("profiles_email_idx").on(t.email) }))
export const sites = pgTable("sites", { id: uuid("id").defaultRandom().primaryKey(), no: integer("no").generatedAlwaysAsIdentity(), namaSite: text("nama_site").notNull(), siteId: text("site_id").notNull(), provinsi: text("provinsi").notNull(), kotaKabupaten: text("kota_kabupaten").notNull(), vlan: text("vlan"), kapasitasBandwidth: text("kapasitas_bandwidth"), mediaAkses: text("media_akses"), picCustomer: text("pic_customer"), noTelpPic: text("no_telp_pic"), picIsp: text("pic_isp"), tanggalAktivasi: date("tanggal_aktivasi"), statusLayanan: text("status_layanan").notNull().default("Aktif"), keterangan: text("keterangan"), archivedAt: timestamp("archived_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, t => ({ siteIdx: uniqueIndex("sites_site_id_idx").on(t.siteId), statusIdx: index("sites_status_idx").on(t.statusLayanan), createdIdx: index("sites_created_idx").on(t.createdAt) }))
const operational = { id: uuid("id").defaultRandom().primaryKey(), siteId: uuid("site_id").notNull().references(() => sites.id, { onDelete: "restrict" }), status: text("status").notNull(), pic: text("pic"), notes: text("notes"), archivedAt: timestamp("archived_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }
export const cids = pgTable("cids", { ...operational, cidNumber: text("cid_number").notNull().unique(), customer: text("customer"), serviceType: text("service_type"), bandwidth: text("bandwidth"), vlan: text("vlan"), ipAddress: text("ip_address"), activationDate: date("activation_date") }, t => ({ siteIdx: index("cids_site_idx").on(t.siteId), statusIdx: index("cids_status_idx").on(t.status) }))
export const fabs = pgTable("fabs", { ...operational, siteId: uuid("site_id").references(() => sites.id, { onDelete: "set null" }),
  fabNumber: text("fab_number").notNull().unique(),
  workflowStatus: text("workflow_status").notNull().default("draft"),
  createdBy: text("created_by").references(() => authUser.id, { onDelete: "set null" }),
  submittedAt: timestamp("submitted_at", { withTimezone: true }), approvedAt: timestamp("approved_at", { withTimezone: true }), approvedBy: text("approved_by").references(() => authUser.id, { onDelete: "set null" }), declarationConfirmed: boolean("declaration_confirmed").notNull().default(false),
  requestDate: date("request_date"), targetDate: date("target_date"), completionDate: date("completion_date"),
  // Step 1: Informasi Kontrak
  contractDate: date("contract_date"), jobType: text("job_type"), previousFabNumber: text("previous_fab_number"),
  // Step 2: Informasi Perusahaan
  companyName: text("company_name"), companyGroup: text("company_group"), businessType: text("business_type"),
  companyAddress: text("company_address"), companyCity: text("company_city"), companyProvinsi: text("company_provinsi"),
  postalCode: text("postal_code"), website: text("website"), companyEmail: text("company_email"),
  npwp: text("npwp"), companyPhone: text("company_phone"),
  // Step 3: PIC & Kontak
  picName: text("pic_name"), picBirthPlace: text("pic_birth_place"), picBirthDate: date("pic_birth_date"),
  picPosition: text("pic_position"), picPhoneCode: text("pic_phone_code"), picPhoneNumber: text("pic_phone_number"),
  picMobileCode: text("pic_mobile_code"), picMobileNumber: text("pic_mobile_number"),
  picIdType: text("pic_id_type"), picIdNumber: text("pic_id_number"), picIdExpiry: date("pic_id_expiry"),
  // Step 4: Jenis Layanan
  serviceType: text("service_type"), bandwidthUp: text("bandwidth_up"), bandwidthDown: text("bandwidth_down"),
  billingType: text("billing_type"), ipType: text("ip_type"), ipAddress: text("ip_address"), slaLevel: text("sla_level"),
  // Step 5: Lokasi & Teknis (site_id from operational base)
  installAddress: text("install_address"), installCity: text("install_city"), installProvinsi: text("install_provinsi"),
  // Step 6: RFS
  rfsDate: date("rfs_date"),
}, t => ({ siteIdx: index("fabs_site_idx").on(t.siteId), statusIdx: index("fabs_status_idx").on(t.status), workflowIdx: index("fabs_workflow_idx").on(t.workflowStatus), createdByIdx: index("fabs_created_by_idx").on(t.createdBy) }))
export const upgrades = pgTable("upgrades", { ...operational, cidId: uuid("cid_id").references(() => cids.id, { onDelete: "set null" }), currentBandwidth: text("current_bandwidth").notNull(), requestedBandwidth: text("requested_bandwidth").notNull(), requestDate: date("request_date"), targetDate: date("target_date"), completionDate: date("completion_date") }, t => ({ siteIdx: index("upgrades_site_idx").on(t.siteId), statusIdx: index("upgrades_status_idx").on(t.status), cidIdx: index("upgrades_cid_idx").on(t.cidId) }))
export const maintenance = pgTable("maintenance", { ...operational, no: integer("no").generatedAlwaysAsIdentity(), cidId: uuid("cid_id").references(() => cids.id, { onDelete: "set null" }), maintenanceType: text("maintenance_type").notNull(), scheduledAt: date("scheduled_at"), startedAt: date("started_at"), completedAt: date("completed_at"), impact: text("impact"), picVendor: text("pic_vendor") }, t => ({ siteIdx: index("maintenance_site_idx").on(t.siteId), statusIdx: index("maintenance_status_idx").on(t.status), cidIdx: index("maintenance_cid_idx").on(t.cidId) }))
export const auditLogs = pgTable("audit_logs", { id: uuid("id").defaultRandom().primaryKey(), userId: text("user_id").notNull().references(() => authUser.id, { onDelete: "cascade" }), action: text("action").notNull(), module: text("module").notNull(), recordId: uuid("record_id"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, t => ({ moduleIdx: index("audit_logs_module_idx").on(t.module), userIdx: index("audit_logs_user_idx").on(t.userId) }))
export const tableMap = { sites, cids, fabs, upgrades, maintenance } as const
export const fabServiceRequests = pgTable("fab_service_requests", { id: uuid("id").defaultRandom().primaryKey(), fabId: uuid("fab_id").notNull().references(() => fabs.id, { onDelete: "cascade" }), sequence: integer("sequence").notNull(), siteId: uuid("site_id").references(() => sites.id, { onDelete: "set null" }), requestedRfsDate: date("requested_rfs_date"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, t => ({ fabIdx: index("fab_service_requests_fab_idx").on(t.fabId), uniqueSequence: uniqueIndex("fab_service_requests_sequence_idx").on(t.fabId, t.sequence) }))
export const fabContacts = pgTable("fab_contacts", { id: uuid("id").defaultRandom().primaryKey(), fabId: uuid("fab_id").notNull().references(() => fabs.id, { onDelete: "cascade" }), serviceRequestId: uuid("service_request_id").references(() => fabServiceRequests.id, { onDelete: "cascade" }), role: text("role").notNull(), name: text("name"), department: text("department"), title: text("title"), email: text("email"), phoneCode: text("phone_code"), phoneNumber: text("phone_number"), phoneExtension: text("phone_extension"), mobileCode: text("mobile_code"), mobileNumber: text("mobile_number"), birthPlace: text("birth_place"), birthDate: date("birth_date"), idType: text("id_type"), idNumber: text("id_number"), idExpiry: date("id_expiry") }, t => ({ fabIdx: index("fab_contacts_fab_idx").on(t.fabId), serviceIdx: index("fab_contacts_service_idx").on(t.serviceRequestId) }))
export const fabServiceProducts = pgTable("fab_service_products", { id: uuid("id").defaultRandom().primaryKey(), serviceRequestId: uuid("service_request_id").notNull().references(() => fabServiceRequests.id, { onDelete: "cascade" }), category: text("category").notNull(), product: text("product").notNull(), package: text("package"), unit: text("unit").notNull(), quantity: numeric("quantity", { precision: 12, scale: 2 }).notNull(), deliveryScope: text("delivery_scope"), uplinkRequired: boolean("uplink_required").notNull().default(false), spaceM2: numeric("space_m2", { precision: 12, scale: 2 }), rackU: numeric("rack_u", { precision: 12, scale: 2 }), powerKva: numeric("power_kva", { precision: 12, scale: 2 }) }, t => ({ serviceIdx: index("fab_service_products_service_idx").on(t.serviceRequestId) }))
export const fabServiceEndpoints = pgTable("fab_service_endpoints", { id: uuid("id").defaultRandom().primaryKey(), serviceRequestId: uuid("service_request_id").notNull().references(() => fabServiceRequests.id, { onDelete: "cascade" }), role: text("role").notNull(), country: text("country"), overseasCarrier: text("overseas_carrier"), companyName: text("company_name"), address: text("address"), latitude: numeric("latitude", { precision: 9, scale: 6 }), longitude: numeric("longitude", { precision: 9, scale: 6 }), picName: text("pic_name"), phone: text("phone"), email: text("email") }, t => ({ serviceIdx: index("fab_service_endpoints_service_idx").on(t.serviceRequestId), uniqueRole: uniqueIndex("fab_service_endpoints_role_idx").on(t.serviceRequestId, t.role) }))
export const fabBillings = pgTable("fab_billings", { id: uuid("id").defaultRandom().primaryKey(), fabId: uuid("fab_id").notNull().references(() => fabs.id, { onDelete: "cascade" }), termMonths: integer("term_months"), billingAddress: text("billing_address"), currency: text("currency").notNull().default("IDR"), vatRate: numeric("vat_rate", { precision: 5, scale: 2 }).notNull().default("0") }, t => ({ fabUnique: uniqueIndex("fab_billings_fab_idx").on(t.fabId) }))
export const fabChargeLines = pgTable("fab_charge_lines", { id: uuid("id").defaultRandom().primaryKey(), billingId: uuid("billing_id").notNull().references(() => fabBillings.id, { onDelete: "cascade" }), type: text("type").notNull(), description: text("description"), serviceAmount: numeric("service_amount", { precision: 18, scale: 2 }).notNull().default("0"), portAmount: numeric("port_amount", { precision: 18, scale: 2 }).notNull().default("0"), localAccessAmount: numeric("local_access_amount", { precision: 18, scale: 2 }).notNull().default("0"), onDemandAmount: numeric("on_demand_amount", { precision: 18, scale: 2 }).notNull().default("0"), scheduleAmount: numeric("schedule_amount", { precision: 18, scale: 2 }).notNull().default("0"), cpeAmount: numeric("cpe_amount", { precision: 18, scale: 2 }).notNull().default("0"), otherAmount: numeric("other_amount", { precision: 18, scale: 2 }).notNull().default("0"), subtotal: numeric("subtotal", { precision: 18, scale: 2 }).notNull().default("0"), vatAmount: numeric("vat_amount", { precision: 18, scale: 2 }).notNull().default("0"), total: numeric("total", { precision: 18, scale: 2 }).notNull().default("0") }, t => ({ billingIdx: index("fab_charge_lines_billing_idx").on(t.billingId) }))
export const fabDocumentVerifications = pgTable("fab_document_verifications", { id: uuid("id").defaultRandom().primaryKey(), fabId: uuid("fab_id").notNull().references(() => fabs.id, { onDelete: "cascade" }), documentType: text("document_type").notNull(), verified: boolean("verified").notNull().default(false), verifiedAt: timestamp("verified_at", { withTimezone: true }), verifiedBy: text("verified_by").references(() => authUser.id, { onDelete: "set null" }) }, t => ({ fabIdx: index("fab_document_verifications_fab_idx").on(t.fabId), uniqueDocument: uniqueIndex("fab_document_verifications_type_idx").on(t.fabId, t.documentType) }))