import { pgTable, text, integer, boolean, date, timestamp, index, uniqueIndex, uuid } from "drizzle-orm/pg-core"
export const authUser = pgTable("user", { id: text("id").primaryKey(), name: text("name").notNull(), email: text("email").notNull().unique(), emailVerified: boolean("email_verified").notNull().default(false), image: text("image"), createdAt: timestamp("created_at").notNull(), updatedAt: timestamp("updated_at").notNull() })
export const authSession = pgTable("session", { id: text("id").primaryKey(), expiresAt: timestamp("expires_at").notNull(), token: text("token").notNull().unique(), createdAt: timestamp("created_at").notNull(), updatedAt: timestamp("updated_at").notNull(), ipAddress: text("ip_address"), userAgent: text("user_agent"), userId: text("user_id").notNull().references(() => authUser.id, { onDelete: "cascade" }) }, t => ({ userIdx: index("session_user_idx").on(t.userId) }))
export const authAccount = pgTable("account", { id: text("id").primaryKey(), accountId: text("account_id").notNull(), providerId: text("provider_id").notNull(), userId: text("user_id").notNull().references(() => authUser.id, { onDelete: "cascade" }), accessToken: text("access_token"), refreshToken: text("refresh_token"), idToken: text("id_token"), accessTokenExpiresAt: timestamp("access_token_expires_at"), refreshTokenExpiresAt: timestamp("refresh_token_expires_at"), scope: text("scope"), password: text("password"), createdAt: timestamp("created_at").notNull(), updatedAt: timestamp("updated_at").notNull() }, t => ({ userIdx: index("account_user_idx").on(t.userId) }))
export const authVerification = pgTable("verification", { id: text("id").primaryKey(), identifier: text("identifier").notNull(), value: text("value").notNull(), expiresAt: timestamp("expires_at").notNull(), createdAt: timestamp("created_at"), updatedAt: timestamp("updated_at") }, t => ({ identifierIdx: index("verification_identifier_idx").on(t.identifier) }))
export const profiles = pgTable("profiles", { id: text("id").primaryKey().references(() => authUser.id, { onDelete: "cascade" }), fullName: text("full_name").notNull(), email: text("email").notNull(), role: text("role").notNull().default("staff"), isActive: boolean("is_active").notNull().default(true), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, t => ({ emailIdx: uniqueIndex("profiles_email_idx").on(t.email) }))
export const sites = pgTable("sites", { id: uuid("id").defaultRandom().primaryKey(), no: integer("no").generatedAlwaysAsIdentity(), namaSite: text("nama_site").notNull(), siteId: text("site_id").notNull(), provinsi: text("provinsi").notNull(), kotaKabupaten: text("kota_kabupaten").notNull(), vlan: text("vlan"), kapasitasBandwidth: text("kapasitas_bandwidth"), mediaAkses: text("media_akses"), picCustomer: text("pic_customer"), noTelpPic: text("no_telp_pic"), picIsp: text("pic_isp"), tanggalAktivasi: date("tanggal_aktivasi"), statusLayanan: text("status_layanan").notNull().default("Aktif"), keterangan: text("keterangan"), archivedAt: timestamp("archived_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, t => ({ siteIdx: uniqueIndex("sites_site_id_idx").on(t.siteId), statusIdx: index("sites_status_idx").on(t.statusLayanan), createdIdx: index("sites_created_idx").on(t.createdAt) }))
const operational = { id: uuid("id").defaultRandom().primaryKey(), siteId: uuid("site_id").notNull().references(() => sites.id, { onDelete: "restrict" }), status: text("status").notNull(), pic: text("pic"), notes: text("notes"), archivedAt: timestamp("archived_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }
export const cids = pgTable("cids", { ...operational, cidNumber: text("cid_number").notNull().unique(), serviceType: text("service_type"), bandwidth: text("bandwidth"), activationDate: date("activation_date") }, t => ({ siteIdx: index("cids_site_idx").on(t.siteId), statusIdx: index("cids_status_idx").on(t.status) }))
export const fabs = pgTable("fabs", { ...operational, fabNumber: text("fab_number").notNull().unique(), requestDate: date("request_date"), targetDate: date("target_date"), completionDate: date("completion_date") }, t => ({ siteIdx: index("fabs_site_idx").on(t.siteId), statusIdx: index("fabs_status_idx").on(t.status) }))
export const upgrades = pgTable("upgrades", { ...operational, currentBandwidth: text("current_bandwidth").notNull(), requestedBandwidth: text("requested_bandwidth").notNull(), requestDate: date("request_date"), targetDate: date("target_date"), completionDate: date("completion_date") }, t => ({ siteIdx: index("upgrades_site_idx").on(t.siteId), statusIdx: index("upgrades_status_idx").on(t.status) }))
export const maintenance = pgTable("maintenance", { ...operational, maintenanceType: text("maintenance_type").notNull(), scheduledAt: date("scheduled_at"), startedAt: date("started_at"), completedAt: date("completed_at"), impact: text("impact"), picVendor: text("pic_vendor") }, t => ({ siteIdx: index("maintenance_site_idx").on(t.siteId), statusIdx: index("maintenance_status_idx").on(t.status) }))
export const auditLogs = pgTable("audit_logs", { id: uuid("id").defaultRandom().primaryKey(), userId: text("user_id").notNull().references(() => authUser.id, { onDelete: "cascade" }), action: text("action").notNull(), module: text("module").notNull(), recordId: uuid("record_id"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, t => ({ moduleIdx: index("audit_logs_module_idx").on(t.module), userIdx: index("audit_logs_user_idx").on(t.userId) }))
export const tableMap = { sites, cids, fabs, upgrades, maintenance } as const
